# Generated by Django 4.0.6 on 2022-07-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_long', models.TextField(blank=True)),
                ('url_short', models.TextField(blank=True)),
                ('time_created', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
